apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pgdemo-memory-hog
  namespace: "pgdemo"
spec:
  annotationCheck: "false"
  engineState: active
  appinfo:
    appns: pgdemo
    applabel: app=pgdemoapp
    appkind: deployment
  chaosServiceAccount: pod-delete-sa
  monitoring: false
  jobCleanUpPolicy: delete
  experiments:
    - name: pod-memory-hog
      spec:
        components:
          env:
            - name: MEMORY_CONSUMPTION
              value: "500"
            - name: TOTAL_CHAOS_DURATION
              value: "60"
